# Generated by Django 6.0.2 on 2026-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Титул')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цитата')),
                ('ability', models.CharField(blank=True, max_length=200, null=True, verbose_name='Способность')),
                ('is_hashira', models.BooleanField(default=False, verbose_name='Столп?')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ранг')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('blood_art', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кровавое искусство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Демон',
                'verbose_name_plural': 'Демоны',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер эпизода')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('air_date', models.DateField(verbose_name='Дата выхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('characters', models.ManyToManyField(blank=True, to='main.character', verbose_name='Персонажи')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['number'],
            },
        ),
    ]
