# Generated by Django 6.0.2 on 2026-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цитата'),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
